/**
 * Declarative field definitions for the 12 master data screens.
 * `relation` fields are populated from /api/master/{path}/options.
 */
export const MASTER_CONFIG = {
  branches: {
    resource: "branch",
    label: "Cabang",
    singular: "Cabang",
    subtitle:
      "Daftar cabang perusahaan. Cabang menjadi acuan lokasi kerja, departemen, dan kebijakan turunan.",
    columns: ["code", "name", "city", "province", "is_head_office"],
    fields: [
      { name: "code", label: "Kode Cabang", required: true, placeholder: "HO", hint: "Huruf besar, unik per perusahaan." },
      { name: "name", label: "Nama Cabang", required: true, placeholder: "Head Office Jakarta" },
      { name: "city", label: "Kota" },
      { name: "province", label: "Provinsi" },
      { name: "postal_code", label: "Kode Pos" },
      { name: "phone", label: "Telepon" },
      { name: "email", label: "Email" },
      { name: "is_head_office", label: "Kantor Pusat", type: "boolean" },
      { name: "address", label: "Alamat", type: "textarea", colSpan: 2 },
      { name: "notes", label: "Catatan", type: "textarea", colSpan: 2 },
    ],
  },
  "work-locations": {
    resource: "work_location",
    label: "Lokasi Kerja",
    singular: "Lokasi Kerja",
    subtitle:
      "Titik lokasi kerja fisik. Dipakai untuk absensi, geofence, dan penempatan proyek pada fase berikutnya.",
    columns: ["code", "name", "branch_id", "location_type", "radius_meter"],
    fields: [
      { name: "code", label: "Kode Lokasi", required: true },
      { name: "name", label: "Nama Lokasi", required: true },
      { name: "branch_id", label: "Cabang", type: "select", relation: "branches" },
      {
        name: "location_type",
        label: "Jenis Lokasi",
        type: "select",
        options: [
          { value: "office", label: "Kantor" },
          { value: "project_site", label: "Site Proyek" },
          { value: "warehouse", label: "Gudang" },
          { value: "client", label: "Lokasi Klien" },
          { value: "remote", label: "Remote" },
        ],
      },
      { name: "latitude", label: "Latitude", type: "number", hint: "Contoh: -6.2265" },
      { name: "longitude", label: "Longitude", type: "number", hint: "Contoh: 106.8097" },
      {
        name: "radius_meter",
        label: "Radius Geofence (meter)",
        type: "number",
        hint: "Jarak maksimal dari titik lokasi agar absensi dianggap di dalam radius.",
      },
      {
        name: "gps_accuracy_max_meter",
        label: "Akurasi GPS Maksimal (meter)",
        type: "number",
        hint: "Absensi dengan akurasi GPS lebih buruk dari batas ini ditandai perlu persetujuan.",
      },
      {
        name: "attendance_location_policy",
        label: "Kebijakan Lokasi Absensi",
        type: "select",
        options: [
          { value: "inside_required", label: "Dalam Radius Wajib" },
          { value: "outside_requires_approval", label: "Di Luar Radius Perlu Persetujuan" },
          { value: "gps_only", label: "GPS Saja (Karyawan Lapangan)" },
          { value: "disabled", label: "Tanpa Geofence" },
        ],
        hint: "Kosongkan untuk mengikuti kebijakan default perusahaan pada Pengaturan Absensi.",
      },
      {
        name: "geofence_enabled",
        label: "Geofence Aktif",
        type: "boolean",
        defaultValue: true,
        hint: "Nonaktifkan untuk mematikan pengecekan radius pada lokasi ini.",
      },
      { name: "address", label: "Alamat", type: "textarea", colSpan: 2 },
      { name: "notes", label: "Catatan", type: "textarea", colSpan: 2 },
    ],
  },
  departments: {
    resource: "department",
    label: "Departemen",
    singular: "Departemen",
    subtitle: "Struktur departemen beserta cabang dan cost center penanggung biaya.",
    columns: ["code", "name", "branch_id", "cost_center_id"],
    fields: [
      { name: "code", label: "Kode Departemen", required: true },
      { name: "name", label: "Nama Departemen", required: true },
      { name: "branch_id", label: "Cabang", type: "select", relation: "branches" },
      { name: "cost_center_id", label: "Cost Center", type: "select", relation: "cost-centers" },
      { name: "parent_id", label: "Departemen Induk", type: "select", relation: "departments", hint: "Kosongkan bila departemen tingkat atas." },
      { name: "description", label: "Deskripsi", type: "textarea", colSpan: 2 },
    ],
  },
  divisions: {
    resource: "division",
    label: "Divisi",
    singular: "Divisi",
    subtitle: "Divisi berada di bawah departemen dan dapat memiliki kebijakan sendiri.",
    columns: ["code", "name", "department_id"],
    fields: [
      { name: "code", label: "Kode Divisi", required: true },
      { name: "name", label: "Nama Divisi", required: true },
      { name: "department_id", label: "Departemen", type: "select", relation: "departments" },
      { name: "description", label: "Deskripsi", type: "textarea", colSpan: 2 },
    ],
  },
  positions: {
    resource: "position",
    label: "Jabatan",
    singular: "Jabatan",
    subtitle: "Jabatan menghubungkan departemen, divisi, dan grade. Dipakai untuk kontrak dan payroll.",
    columns: ["code", "name", "department_id", "division_id", "job_grade_id", "is_supervisory"],
    fields: [
      { name: "code", label: "Kode Jabatan", required: true },
      { name: "name", label: "Nama Jabatan", required: true },
      { name: "department_id", label: "Departemen", type: "select", relation: "departments" },
      { name: "division_id", label: "Divisi", type: "select", relation: "divisions" },
      { name: "job_grade_id", label: "Grade / Level", type: "select", relation: "job-grades" },
      { name: "reports_to_position_id", label: "Melapor Kepada", type: "select", relation: "positions" },
      { name: "is_supervisory", label: "Jabatan Atasan", type: "boolean", hint: "Aktifkan bila jabatan ini menyetujui pengajuan tim." },
      { name: "description", label: "Deskripsi", type: "textarea", colSpan: 2 },
    ],
  },
  "job-grades": {
    resource: "job_grade",
    label: "Grade / Level",
    singular: "Grade",
    subtitle: "Tingkatan jabatan beserta rentang gaji sebagai acuan payroll.",
    columns: ["code", "name", "level", "min_salary", "max_salary"],
    fields: [
      { name: "code", label: "Kode Grade", required: true },
      { name: "name", label: "Nama Grade", required: true },
      { name: "level", label: "Level (angka)", type: "number", hint: "Semakin besar semakin tinggi." },
      { name: "min_salary", label: "Gaji Minimum", type: "number" },
      { name: "max_salary", label: "Gaji Maksimum", type: "number" },
      { name: "description", label: "Deskripsi", type: "textarea", colSpan: 2 },
    ],
    currencyFields: ["min_salary", "max_salary"],
  },
  "cost-centers": {
    resource: "cost_center",
    label: "Cost Center",
    singular: "Cost Center",
    subtitle: "Pusat biaya untuk membebankan gaji, biaya proyek, dan permintaan dana.",
    columns: ["code", "name", "branch_id"],
    fields: [
      { name: "code", label: "Kode Cost Center", required: true },
      { name: "name", label: "Nama Cost Center", required: true },
      { name: "branch_id", label: "Cabang", type: "select", relation: "branches" },
      { name: "description", label: "Deskripsi", type: "textarea", colSpan: 2 },
    ],
  },
  projects: {
    resource: "project",
    label: "Proyek",
    singular: "Proyek",
    subtitle: "Proyek/kontrak klien. Menjadi cakupan penempatan karyawan dan kebijakan khusus.",
    columns: ["code", "name", "client_name", "start_date", "end_date", "contract_value"],
    fields: [
      { name: "code", label: "Kode Proyek", required: true },
      { name: "name", label: "Nama Proyek", required: true },
      { name: "client_name", label: "Nama Klien" },
      { name: "branch_id", label: "Cabang", type: "select", relation: "branches" },
      { name: "work_location_id", label: "Lokasi Kerja", type: "select", relation: "work-locations" },
      { name: "cost_center_id", label: "Cost Center", type: "select", relation: "cost-centers" },
      { name: "start_date", label: "Tanggal Mulai", type: "date" },
      { name: "end_date", label: "Tanggal Berakhir", type: "date" },
      { name: "contract_value", label: "Nilai Kontrak", type: "number" },
      { name: "description", label: "Deskripsi", type: "textarea", colSpan: 2 },
    ],
    currencyFields: ["contract_value"],
    dateFields: ["start_date", "end_date"],
  },
  "employment-statuses": {
    resource: "employment_status",
    label: "Status Kepegawaian",
    singular: "Status Kepegawaian",
    subtitle: "Contoh: Karyawan Tetap (PKWTT), Kontrak (PKWT), Harian Lepas, Magang.",
    columns: ["code", "name", "is_permanent", "requires_contract"],
    fields: [
      { name: "code", label: "Kode", required: true },
      { name: "name", label: "Nama Status", required: true },
      { name: "is_permanent", label: "Karyawan Tetap", type: "boolean" },
      { name: "requires_contract", label: "Wajib Kontrak", type: "boolean" },
      { name: "description", label: "Deskripsi", type: "textarea", colSpan: 2 },
    ],
  },
  "contract-types": {
    resource: "contract_type",
    label: "Tipe Kontrak",
    singular: "Tipe Kontrak",
    subtitle: "Pola kontrak kerja beserta durasi dan aturan perpanjangan.",
    columns: ["code", "name", "duration_months", "is_extendable", "max_extension"],
    fields: [
      { name: "code", label: "Kode", required: true },
      { name: "name", label: "Nama Tipe Kontrak", required: true },
      { name: "duration_months", label: "Durasi (bulan)", type: "number" },
      { name: "is_extendable", label: "Dapat Diperpanjang", type: "boolean" },
      { name: "max_extension", label: "Maksimal Perpanjangan", type: "number" },
      { name: "description", label: "Deskripsi", type: "textarea", colSpan: 2 },
    ],
  },
  "certification-types": {
    resource: "certification_type",
    label: "Tipe Sertifikasi",
    singular: "Tipe Sertifikasi",
    subtitle: "Sertifikasi wajib/opsional beserta masa berlaku dan pengingatnya.",
    columns: ["code", "name", "issuing_body", "validity_months", "is_mandatory"],
    fields: [
      { name: "code", label: "Kode", required: true },
      { name: "name", label: "Nama Sertifikasi", required: true },
      { name: "issuing_body", label: "Penerbit" },
      { name: "validity_months", label: "Masa Berlaku (bulan)", type: "number" },
      { name: "reminder_days", label: "Ingatkan (hari sebelum)", type: "number" },
      { name: "is_mandatory", label: "Wajib", type: "boolean" },
      { name: "description", label: "Deskripsi", type: "textarea", colSpan: 2 },
    ],
  },
  "document-types": {
    resource: "document_type",
    label: "Tipe Dokumen",
    singular: "Tipe Dokumen",
    subtitle:
      "Definisi jenis dokumen (CV, KTP, Ijazah, Kontrak, dst) beserta format dan batas ukuran berkas.",
    columns: ["code", "name", "category", "owner_scope", "has_expiry", "max_size_mb"],
    fields: [
      { name: "code", label: "Kode", required: true },
      { name: "name", label: "Nama Tipe Dokumen", required: true },
      { name: "category", label: "Kategori", placeholder: "Identitas / Kontrak / Keuangan" },
      {
        name: "owner_scope",
        label: "Pemilik Dokumen",
        type: "select",
        options: [
          { value: "company", label: "Perusahaan" },
          { value: "employee", label: "Karyawan" },
          { value: "applicant", label: "Pelamar" },
          { value: "contract", label: "Kontrak Kerja" },
          { value: "certification", label: "Sertifikasi" },
          { value: "project", label: "Proyek" },
          { value: "invoice", label: "Invoice" },
          { value: "travel", label: "Tiket / Perjalanan" },
          { value: "receipt", label: "Kwitansi" },
          { value: "medical", label: "Dokumen Medis" },
          { value: "other", label: "Lainnya" },
        ],
      },
      { name: "is_mandatory", label: "Wajib Dilengkapi", type: "boolean" },
      { name: "has_expiry", label: "Punya Masa Berlaku", type: "boolean" },
      { name: "reminder_days", label: "Ingatkan (hari sebelum)", type: "number" },
      { name: "allowed_extensions", label: "Format Diizinkan", placeholder: "pdf,jpg,png", hint: "Pisahkan dengan koma." },
      { name: "max_size_mb", label: "Maksimal Ukuran (MB)", type: "number" },
      { name: "description", label: "Deskripsi", type: "textarea", colSpan: 2 },
    ],
  },
};

export const COLUMN_LABELS = {
  code: "Kode",
  name: "Nama",
  city: "Kota",
  province: "Provinsi",
  is_head_office: "Kantor Pusat",
  branch_id: "Cabang",
  location_type: "Jenis",
  radius_meter: "Radius (m)",
  cost_center_id: "Cost Center",
  department_id: "Departemen",
  division_id: "Divisi",
  job_grade_id: "Grade",
  is_supervisory: "Atasan",
  level: "Level",
  min_salary: "Gaji Min",
  max_salary: "Gaji Maks",
  client_name: "Klien",
  start_date: "Mulai",
  end_date: "Berakhir",
  contract_value: "Nilai Kontrak",
  is_permanent: "Tetap",
  requires_contract: "Wajib Kontrak",
  duration_months: "Durasi (bln)",
  is_extendable: "Perpanjangan",
  max_extension: "Maks Perpanjangan",
  issuing_body: "Penerbit",
  validity_months: "Masa Berlaku (bln)",
  is_mandatory: "Wajib",
  category: "Kategori",
  owner_scope: "Pemilik",
  has_expiry: "Masa Berlaku",
  max_size_mb: "Maks (MB)",
};

export const LOCATION_TYPE_LABELS = {
  office: "Kantor",
  project_site: "Site Proyek",
  warehouse: "Gudang",
  client: "Lokasi Klien",
  remote: "Remote",
};
